import {useCallback,useEffect,useRef,useState} from 'react';
import {api,BASE,setCsrf,upload,type Lesson,type Artifact,type Prefs,type Task} from './api';
import {Pdf,Share} from './Pdf';
import {Dialog} from './Dialog';

type Page='Library'|'Activity'|'Resources'|'Settings';
const readable=(value:string)=>value.toLowerCase().replaceAll('_',' ').replace(/^./,s=>s.toUpperCase());
const bytes=(value:number|null|undefined)=>value==null?'Unavailable':(value/1073741824).toFixed(1)+' GiB';
const terminal=new Set(['COMPLETED','CANCELLED','EXHAUSTED','FAILED','NEEDS_ATTENTION']);
function Icon({name}:{name:string}){return <span aria-hidden="true" className="nav-icon">{{Library:'▦',Activity:'◷',Resources:'⌁',Settings:'⚙'}[name]||'+'}</span>;}

export default function App(){
  const [page,setPage]=useState<Page>('Library');const [prefs,setPrefs]=useState<Prefs|null>(null);
  const [error,setError]=useState('');const [notice,setNotice]=useState('');const [ready,setReady]=useState(false);
  const [offline,setOffline]=useState(!navigator.onLine);const [connected,setConnected]=useState(false);const [revision,refresh]=useState(0);
  const [selected,setSelected]=useState<Lesson|null>(null);const [suggested,setSuggested]=useState<Lesson|null>(null);const [preview,setPreview]=useState<Artifact|null>(null);
  const [update,setUpdate]=useState<ServiceWorker|null>(null);const [install,setInstall]=useState<any>(null);
  const notify=useCallback((message:string)=>setNotice(message),[]);
  const reload=useCallback(()=>refresh(x=>x+1),[]);
  useEffect(()=>{let gone=false;api('session').then(s=>{if(!gone){setCsrf(s.csrf);setPrefs(s.preferences);setReady(true);}}).catch(e=>setError(e.message));
    const connection=(e:Event)=>setConnected((e as CustomEvent<boolean>).detail);window.addEventListener('connection',connection);
    const online=()=>setOffline(!navigator.onLine);window.addEventListener('online',online);window.addEventListener('offline',online);
    const installable=(e:Event)=>{e.preventDefault();setInstall(e);};window.addEventListener('beforeinstallprompt',installable);
    if('serviceWorker' in navigator)void navigator.serviceWorker.register(BASE+'sw.js',{scope:BASE}).then(r=>{
      if(r.waiting)setUpdate(r.waiting);r.addEventListener('updatefound',()=>{const w=r.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)setUpdate(w);});});
    }).catch(()=>{});
    return()=>{gone=true;window.removeEventListener('connection',connection);window.removeEventListener('online',online);window.removeEventListener('offline',online);window.removeEventListener('beforeinstallprompt',installable);};
  },[]);
  useEffect(()=>{document.documentElement.dataset.theme=prefs?.theme||'system';},[prefs?.theme]);
  useEffect(()=>{if(!ready||offline)return;const stream=new EventSource(BASE+'api/events');
    let queued:number|undefined;
    const schedule=()=>{if(queued===undefined)queued=window.setTimeout(()=>{queued=undefined;reload();},350);};
    stream.onopen=()=>{setConnected(true);void api<Prefs>('preferences').then(setPrefs).catch(()=>{});};stream.onerror=()=>setConnected(false);
    stream.onmessage=schedule;stream.addEventListener('reset',schedule);
    stream.addEventListener('preferences',()=>{void api<Prefs>('preferences').then(setPrefs).catch(()=>{});});
    const poll=window.setInterval(reload,15000);return()=>{stream.close();clearInterval(poll);clearTimeout(queued);};
  },[ready,offline,reload]);
  useEffect(()=>{if(notice){const id=setTimeout(()=>setNotice(''),8000);return()=>clearTimeout(id);}},[notice]);
  const save=async(value:Partial<Prefs>,version?:number)=>{if(!prefs)return;const updated=await api<Prefs>('preferences',{method:'PATCH',body:JSON.stringify({version:version??prefs.version,value})});setPrefs(updated);notify('Settings saved for all your devices.');};
  const navigate=(next:Page)=>{setPage(next);setSelected(null);setSuggested(null);};
  return <div className="app"><aside className="sidebar"><a className="brand" href={BASE} aria-label="Vocabatron home"><img src={BASE+'icons/mark.svg'} alt=""/>Vocabatron</a><div className="workspace"><span className="avatar">V</span><div>My workspace<small>Private · shared across devices</small></div></div>
    <nav aria-label="Main navigation">{(['Library','Activity','Resources','Settings'] as Page[]).map(name=><button key={name} className={page===name?'active':''} onClick={()=>navigate(name)} aria-current={page===name?'page':undefined}><Icon name={name}/>{name}</button>)}</nav>
    <div className="sidebar-foot"><span className={'dot '+(offline||!connected?'muted':'')}/>{offline?'Offline':connected?'Private connection':'Reconnecting…'}<small>Your files stay on your server.</small></div></aside>
    <main><header className="topbar"><span>{selected?<><button className="text-button" onClick={()=>setSelected(null)}>Library</button> / Lesson {selected.number}</>:page}</span><span className="quiet">One library. Every device.</span></header>
      {offline&&<div className="banner" role="status">You are offline. The app shell is available; connect to your private network to view files or make changes. Server tasks continue independently.</div>}
      {ready&&!offline&&!connected&&<div className="banner" role="status">Connection interrupted. Displayed information may be out of date. Reconnecting to your server…</div>}
      {update&&<div className="banner">An app update is ready. Finish any upload before reloading. <button onClick={()=>{navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});update.postMessage('ACTIVATE_UPDATE');}}>Update and reload</button></div>}
      {notice&&<div className="toast" role="status">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</button></div>}
      {!ready?<div className="empty"><h1>{error?'Connection unavailable':'Opening your workspace…'}</h1><p>{error||'Checking your private connection.'}</p>{error&&<><p>Connect to your Tailscale network and open the private app address. Your login must be authorized.</p><button onClick={()=>location.reload()}>Try again</button></>}</div>:<div className="content">
        {page==='Library'&&(selected?<Results lesson={selected} revision={revision} notify={notify} preview={setPreview} changed={value=>{setSelected(value);reload();}} generate={()=>{setSuggested(selected);setSelected(null);}}/>:<Library prefs={prefs!} revision={revision} refresh={reload} notify={notify} onOpen={l=>{setSuggested(null);setSelected(l);}} save={save} suggested={suggested}/>)}
        {page==='Activity'&&<Activity revision={revision} refresh={reload} notify={notify} open={async id=>{try{const lesson=await api<Lesson>('lessons/'+id);setSelected(lesson);setPage('Library');}catch(e){notify(String(e));}}}/>}
        {page==='Resources'&&<Resources revision={revision}/>}
        {page==='Settings'&&<Settings prefs={prefs!} save={save} notify={notify} install={install} installed={()=>setInstall(null)}/>}
      </div>}
    </main>{preview&&<Pdf artifact={preview} onClose={()=>setPreview(null)}/>}</div>;
}

function Library({prefs,revision,refresh,notify,onOpen,save,suggested}:{prefs:Prefs;revision:number;refresh:()=>void;notify:(v:string)=>void;onOpen:(v:Lesson)=>void;save:(v:Partial<Prefs>)=>Promise<void>;suggested:Lesson|null}){
  const [archived,setArchived]=useState(false);const [items,setItems]=useState<Lesson[]>([]);const [total,setTotal]=useState(0);const [query,setQuery]=useState('');const [offset,setOffset]=useState(0);
  const [chosen,setChosen]=useState<Record<string,Lesson>>(suggested?{[suggested.id]:suggested}:{});const [count,setCount]=useState(String(prefs.default_count));const [all,setAll]=useState(false);
  const [overrides,setOverrides]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [progress,setProgress]=useState<number|null>(null);const [error,setError]=useState('');const [drag,setDrag]=useState(false);
  const [sources,setSources]=useState<any[]>([]);const [importHistory,setImportHistory]=useState(false);const [sourceDetails,setSourceDetails]=useState<any>(null);const input=useRef<HTMLInputElement>(null);const key=useRef<string|null>(null);const submitting=useRef(false);
  useEffect(()=>{let gone=false;const timer=setTimeout(()=>{api('lessons?q='+encodeURIComponent(query)+'&offset='+offset+'&archived='+archived).then(v=>{if(!gone){setItems(v.items);setTotal(v.total);setError('');}}).catch(e=>!gone&&setError(e.message));},200);return()=>{gone=true;clearTimeout(timer);};},[query,offset,revision,archived]);
  useEffect(()=>{if(!Object.keys(chosen).length)setCount(String(prefs.default_count));},[prefs.default_count]);
  useEffect(()=>{void api('sources?history='+importHistory).then(v=>setSources(v.items.filter((s:any)=>importHistory||s.status!=='READY'))).catch(()=>{});},[revision,importHistory]);
  const noticeAction=async(id:string,restore=false)=>{try{await api('sources/'+id+'/'+(restore?'restore-notice':'dismiss'),{method:'POST'});refresh();}catch(e){notify(String(e));}};
  const send=async(files:File[])=>{if(!files.length||busy)return;if(files.some(f=>!f.name.toLowerCase().endsWith('.pdf'))){notify('Choose PDF files only.');return;}setBusy(true);setProgress(0);
    try{const result=await upload(files,(sent,total)=>setProgress(total?Math.round(sent/total*100):null));notify(result.items.every((x:any)=>x.reused)?'These documents are already in your library.':'Upload received. Import will continue in Activity.');refresh();}catch(e){notify(String(e));}finally{setBusy(false);setProgress(null);if(input.current)input.current.value='';}};
  const generate=async()=>{if(submitting.current)return;const targets=Object.values(chosen).map(l=>({lesson_id:l.id,mode:all?'all':'count',count:all?null:Number(overrides[l.id]||count)}));
    if(!targets.length||targets.some(t=>t.mode==='count'&&(!Number.isSafeInteger(t.count)||t.count!<1))){notify('Enter a positive whole number for every lesson.');return;}
    submitting.current=true;setBusy(true);key.current??=crypto.randomUUID();
    try{await api('generate',{method:'POST',body:JSON.stringify({idempotency_key:key.current,targets})});key.current=null;setChosen({});refresh();notify('Request queued. You can close this page; Activity shows live progress.');}catch(e){notify(String(e));}finally{submitting.current=false;setBusy(false);}};
  const toggle=(l:Lesson)=>{key.current=null;setChosen(old=>{const value={...old};if(value[l.id])delete value[l.id];else value[l.id]=l;return value;});};
  return <><div className="page-heading"><div><span className="eyebrow">YOUR VOCABULARY, READY TO USE</span><h1>Lesson library</h1><p>Turn your lessons into a fresh set of crosswords.</p></div><button className="primary" disabled={busy} onClick={()=>input.current?.click()}>＋ Upload PDFs</button></div>
    <input ref={input} className="visually-hidden" type="file" accept="application/pdf,.pdf" multiple aria-label="Upload PDF documents" onChange={e=>void send(Array.from(e.target.files||[]))}/>
    <div className={'dropzone '+(drag?'drag':'')} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);void send(Array.from(e.dataTransfer.files));}}><div className="upload-glyph">↥</div><div><strong>{busy&&progress!==null?'Uploading · '+progress+'%':'Drop your lesson PDFs here'}</strong><p>Single lessons or books. Import runs in the background.</p></div><button disabled={busy} onClick={()=>input.current?.click()}>Browse files</button></div>
    <div className="section-toolbar"><button aria-pressed={importHistory} onClick={()=>setImportHistory(!importHistory)}>{importHistory?'Hide import history':'Import history'}</button></div>{sources.length>0&&<details className="panel" open={importHistory}><summary>{importHistory?'Import history':'Import notices'} · {sources.length} document{sources.length!==1?'s':''}</summary>{sources.map(s=><div className="source-row" key={s.id}><span>{s.name}<small>{readable(s.status)}</small></span>{s.report&&<button onClick={async()=>{try{const report=await api('sources/'+s.id+'/report');setSourceDetails({...report,id:s.id,name:s.name});}catch(e){notify(String(e));}}}>View details</button>}{['READY','PARTIALLY_IMPORTED','NEEDS_ATTENTION','FAILED','CANCELLED','RECOVERY_UNAVAILABLE'].includes(s.status)&&(s.notice_dismissed_at?<button onClick={()=>void noticeAction(s.id,true)}>Restore notice</button>:<button aria-label="Dismiss import notice" title="Dismiss import notice" onClick={()=>void noticeAction(s.id)}>×</button>)}</div>)}</details>}
    <div className="section-toolbar"><h2>{archived?'Archived lessons':'All lessons'} <span className="count">{total}</span></h2><select aria-label="Library view" value={archived?'archived':'active'} onChange={e=>{setArchived(e.target.value==='archived');setChosen({});setOffset(0);}}><option value="active">Active</option><option value="archived">Archived</option></select><input type="search" placeholder="Search lessons…" aria-label="Search lessons" value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></div>
    {error&&<p className="error" role="alert">{error}</p>}
    {items.length===0?(error?null:<div className="empty panel"><div className="empty-mark">▦</div><h2>{query?'No matching lessons':'Your next crossword starts here'}</h2><p>{query?'Try a lesson number, name, or content ID.':'Upload a PDF to add your first lesson. Original wording stays intact.'}</p></div>):<div className="lesson-grid">{items.map(l=><article className={'lesson-card '+(chosen[l.id]?'selected':'')} key={l.id}><div className="card-top"><span className="lesson-tag">LESSON {String(l.number).padStart(2,'0')}</span><label className="check"><input type="checkbox" disabled={archived} checked={!!chosen[l.id]} onChange={()=>toggle(l)} aria-label={'Select Lesson '+l.number+' '+l.content_short_id}/></label></div><button className="card-title" onClick={()=>onOpen(l)}>{l.display_name||'Lesson '+l.number}</button><p>{l.word_count} words <span>·</span> {l.variants} saved variants</p><div className="source-name" title={l.sources.map(s=>s.name).join(', ')}>{l.sources[0]?.name||'Imported lesson'}</div><code className="content-id">{l.content_short_id}</code><footer><span className="status"><span className="dot"/>{l.status}</span><button className="text-button" onClick={()=>onOpen(l)}>Open →</button></footer></article>)}</div>}
    <Pagination offset={offset} total={total} size={30} setOffset={setOffset}/>
    {sourceDetails&&<Dialog title="Import details" close={()=>setSourceDetails(null)}><p>{sourceDetails.name}</p>{sourceDetails.attempts?.length>1&&<label>Import attempt<select value={sourceDetails.selectedTask||''} onChange={async e=>{const selectedTask=e.target.value;try{const report=await api('sources/'+sourceDetails.id+'/report'+(selectedTask?'?task_id='+selectedTask:''));setSourceDetails({...report,id:sourceDetails.id,name:sourceDetails.name,selectedTask});}catch(error){notify(String(error));}}}><option value="">Latest result</option>{sourceDetails.attempts.filter((a:any)=>a.report).map((a:any)=><option key={a.task_id} value={a.task_id}>{new Date(a.created*1000).toLocaleString()}</option>)}</select></label>}{sourceDetails.timings&&<p className="hint">Processing: {sourceDetails.timings.processing_seconds.toFixed(2)}s · Queue: {sourceDetails.timings.queue_wait_seconds.toFixed(2)}s · Resource wait: {sourceDetails.timings.resource_wait_seconds.toFixed(2)}s</p>}{sourceDetails.recovery_errors?.map((e:any,i:number)=><p role="status" key={i}>{readable(e.code)} · Page {e.page}</p>)}<a className="button" href={BASE+'api/sources/'+sourceDetails.id+'/pdf?download=1'}>Download original PDF</a>{sourceDetails.lessons?.map((l:any,i:number)=><div className="panel" key={i}><h3>Lesson {l.number}</h3><p>{readable(l.status||'Checking')}</p>{l.errors?.map((e:any,j:number)=><p key={j}>{readable(e.code)} · {e.page?'Page '+e.page:'Pages '+(e.pages||[]).join(', ')}</p>)}</div>)}{sourceDetails.issues?.map((e:any,i:number)=><div className="panel" key={i}><strong>{readable(e.code)}</strong><p>Page {e.page}</p>{e.text&&<blockquote>{e.text}</blockquote>}</div>)}</Dialog>}{Object.keys(chosen).length>0&&<section className="generation panel"><div><h2>{Object.keys(chosen).length} lesson{Object.keys(chosen).length>1?'s':''} selected</h2><p>Each variant is a verified, two-page PDF.</p></div><div className="generation-controls"><label>Variants per lesson<input type="number" min="1" step="1" disabled={all} value={count} onChange={e=>{setCount(e.target.value);key.current=null;}}/></label><label className="checkbox"><input type="checkbox" checked={all} onChange={e=>{setAll(e.target.checked);key.current=null;}}/>Find all remaining structures</label></div>
      {all?<p className="hint">This can run for a long time. Results appear as they are verified. “Exhausted” requires a complete proof; you can pause at any time.</p>:<details><summary>Per-lesson counts and default</summary>{Object.values(chosen).map(l=><label className="override" key={l.id}>Lesson {l.number} · {l.content_short_id}<input aria-label={'Count for '+l.content_short_id} type="number" min="1" value={overrides[l.id]??''} placeholder={count} onChange={e=>{setOverrides({...overrides,[l.id]:e.target.value});key.current=null;}}/></label>)}<button onClick={()=>void save({default_count:Number(count)}).catch(e=>notify(e.message))}>Save {count} as my default</button></details>}
      <div className="actions"><button onClick={async()=>{try{for(const l of Object.values(chosen))await api('prepare',{method:'POST',body:JSON.stringify({lesson_id:l.id})});refresh();notify('Clue preparation queued.');}catch(e){notify(String(e));}}}>Prepare clues</button><button onClick={()=>setChosen({})}>Clear selection</button><button className="primary" disabled={busy} onClick={()=>void generate()}>{busy?'Submitting…':'Generate variants →'}</button></div></section>}
  </>;
}

function Pagination({offset,total,size,setOffset}:{offset:number;total:number;size:number;setOffset:(n:number)=>void}){if(total<=size)return null;return <div className="pagination"><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-size))}>Previous</button><span>{offset+1}–{Math.min(total,offset+size)} of {total}</span><button disabled={offset+size>=total} onClick={()=>setOffset(offset+size)}>Next</button></div>;}
function Results({lesson,revision,notify,preview,generate,changed}:{lesson:Lesson;revision:number;notify:(s:string)=>void;preview:(a:Artifact)=>void;generate:()=>void;changed:(lesson:Lesson)=>void}){
  const [transcript,setTranscript]=useState<any>(null);const [editing,setEditing]=useState(false);const [name,setName]=useState(lesson.display_name||'');
  const edit=async(value:{display_name?:string;archived?:boolean})=>{try{await api('lessons/'+lesson.id,{method:'PATCH',body:JSON.stringify(value)});changed(await api<Lesson>('lessons/'+lesson.id));setEditing(false);notify(value.archived===undefined?'Display name saved.':value.archived?'Lesson archived. Saved results and history are retained.':'Lesson returned to the library.');}catch(e){notify(String(e));}};
  const [items,setItems]=useState<Artifact[]>([]);const [offset,setOffset]=useState(0);const [total,setTotal]=useState(0);const [error,setError]=useState('');
  useEffect(()=>{void api('restore',{method:'POST',body:JSON.stringify({lesson_id:lesson.id})}).catch(e=>notify(e.message));},[lesson.id]);
  useEffect(()=>{let gone=false;api('lessons/'+lesson.id+'/results?offset='+offset).then(r=>{if(!gone){setItems(r.items);setTotal(r.total);setError('');}}).catch(e=>!gone&&setError(e.message));return()=>{gone=true;};},[lesson.id,offset,revision]);
  const restore=async()=>{try{await api('restore',{method:'POST',body:JSON.stringify({lesson_id:lesson.id})});notify('Export restoration queued. Saved PDFs will be copied without generating new puzzles.');}catch(e){notify(String(e));}};
  return <><div className="page-heading"><div><span className="eyebrow">{lesson.content_short_id} · {lesson.word_count} WORDS</span><h1>{lesson.display_name||'Lesson '+lesson.number}</h1><p>Your saved crossword collection.</p></div><button className="primary" disabled={!!lesson.archived} onClick={generate}>Generate more</button></div><div className="actions"><button onClick={async()=>{try{setTranscript(await api('lessons/'+lesson.id+'/transcript'));}catch(e){notify(String(e));}}}>View source text</button><button onClick={()=>{setName(lesson.display_name||'');setEditing(true);}}>Rename</button><button onClick={()=>{if(lesson.archived||confirm('Archive this lesson? Saved PDFs and structure history will be retained.'))void edit({archived:!lesson.archived});}}>{lesson.archived?'Unarchive lesson':'Archive lesson'}</button></div>{transcript&&<Dialog title="Source text" close={()=>setTranscript(null)}><p>Original document · Pages {transcript.pages.join(', ')}</p><a className="button" href={BASE+'api/sources/'+transcript.source_id+'/pdf?download=1'}>Download source PDF</a><pre className="transcript">{transcript.text}</pre></Dialog>}{editing&&<Dialog title="Rename lesson" close={()=>setEditing(false)}><label>Display name <input aria-label="Display name" value={name} maxLength={100} onChange={e=>setName(e.target.value)}/></label><p>The source text, content identity, and history stay intact.</p><button className="primary" onClick={()=>void edit({display_name:name})}>Save name</button></Dialog>}<div className="section-toolbar"><h2>Saved variants <span className="count">{total}</span></h2><button onClick={()=>void restore()}>Restore exports</button></div>{error&&<p role="alert">{error}</p>}
    {!items.length?<div className="empty panel"><h2>No variants yet</h2><p>Select this lesson in the library and choose how many to generate.</p></div>:<div className="result-grid">{items.map(a=><article className="result-card" key={a.id}><button className="paper-preview" onClick={()=>preview(a)} aria-label={'Preview variant '+a.variant_number}><div className="document-symbol" aria-hidden="true">PDF<span>2 pages</span></div><span>Preview PDF ↗</span></button><div className="result-body"><span className="eyebrow">BATCH {String(a.batch_number).padStart(4,'0')}</span><h3>Variant {String(a.variant_number).padStart(3,'0')}</h3><p>2 pages · {a.crossing_count} crossings · {Math.ceil(a.bytes/1024)} KB</p><small>{a.export_status==='AVAILABLE'?'Export saved':readable(a.export_status||'Export pending')}</small><div className="actions"><a className="button primary" href={BASE+'api/artifacts/'+a.id+'/pdf?download=1'}>Download PDF</a><Share artifact={a} notify={notify}/></div>{a.export_status==='CONFLICT'&&<p className="hint">An existing export has different contents. Rename that file in Outputs, then restore exports.</p>}</div></article>)}</div>}<Pagination offset={offset} total={total} size={20} setOffset={setOffset}/></>;
}

function Activity({revision,refresh,notify,open}:{revision:number;refresh:()=>void;notify:(s:string)=>void;open:(id:string)=>void}){
  const [items,setItems]=useState<Task[]>([]);const [error,setError]=useState('');const [offset,setOffset]=useState(0);const [total,setTotal]=useState(0);const [history,setHistory]=useState(false);
  useEffect(()=>{void api('tasks?offset='+offset+'&history='+history).then(r=>{setItems(r.items);setTotal(r.total);setError('');}).catch(e=>setError(e.message));},[revision,offset,history]);
  const dismissCompleted=async()=>{try{await api('tasks/dismiss-completed',{method:'POST'});setOffset(0);refresh();}catch(e){notify(String(e));}};
  const control=async(t:Task,action:string)=>{if(action==='cancel'&&!confirm('Cancel remaining work? Verified results will be kept.'))return;try{await api('tasks/'+t.id+'/'+action,{method:'POST'});refresh();}catch(e){notify(String(e));}};
  return <><div className="page-heading"><div><span className="eyebrow">WORK CONTINUES WHEN YOU LEAVE</span><h1>Activity</h1><p>Live progress, saved results, and clear next steps.</p></div><div className="actions"><button aria-pressed={history} onClick={()=>{setHistory(!history);setOffset(0);}}>{history?'Active view':'History'}</button><button onClick={()=>void dismissCompleted()}>Dismiss completed</button><button onClick={refresh}>Refresh</button></div></div>{error&&<p role="alert">{error}</p>}{!items.length?<div className="empty panel"><h2>All quiet here</h2><p>Uploads and generation requests will appear here.</p></div>:<div className="task-list">{items.map(t=><article className="task panel" key={t.id}><div className="task-header"><div><small>{t.kind.toUpperCase()} {t.lesson_number!=null?'· LESSON '+t.lesson_number:''}</small><h2>{readable(t.status)}</h2></div><span className={'status-pill '+(terminal.has(t.status)?'settled':'')}>{t.kind==='generate'?t.completed+' / '+(t.target_type==='all'?'all':t.target_count)+' verified':readable(t.stage)}</span>{terminal.has(t.status)&&!t.dismissed_at&&<button aria-label="Dismiss activity" title="Dismiss activity" onClick={()=>void control(t,'dismiss')}>×</button>}</div><p>{readable(t.stage)}{t.detail?.pages_total!=null&&` · Page ${Math.min((t.detail.pages_done||0)+1,t.detail.pages_total)} of ${t.detail.pages_total}`}</p>{t.pending_variants>0&&<p className="hint">{t.pending_variants} discovered variant{t.pending_variants>1?'s':''} waiting for PDF verification.</p>}{t.detail&&<p className="hint">{typeof t.detail==='string'?t.detail:t.detail.message||t.detail.reason||t.detail.error||''}</p>}<footer><code>{t.id.slice(0,12)}</code><div className="actions">{t.lesson_id&&t.completed>0&&<button onClick={()=>open(t.lesson_id)}>View results</button>}{!terminal.has(t.status)&&<><button onClick={()=>void control(t,t.status==='PAUSED_BY_USER'?'resume':'pause')}>{t.status==='PAUSED_BY_USER'?'Resume':'Pause'}</button><button onClick={()=>void control(t,'cancel')}>Cancel</button></>}{terminal.has(t.status)&&t.dismissed_at&&<button onClick={()=>void control(t,'restore-activity')}>Restore activity</button>}{['FAILED','NEEDS_ATTENTION','INTERRUPTED'].includes(t.status)&&<button onClick={()=>void control(t,'retry')}>Retry</button>}</div></footer></article>)}</div>}<Pagination offset={offset} total={total} size={50} setOffset={setOffset}/></>;
}

function Resources({revision}:{revision:number}){
  const [data,setData]=useState<any>(null);const [error,setError]=useState('');useEffect(()=>{void api('resources').then(setData).catch(e=>setError(e.message));},[revision]);
  if(!data)return <p role="status">{error||'Reading resource telemetry…'}</p>;
  const age=data.sample?Math.max(0,Date.now()/1000-data.sample.sampled_at):null;const stale=age===null||age>data.stale_seconds;const s=stale?null:data.sample;
  return <><div className="page-heading"><div><span className="eyebrow">OTHER APPLICATIONS COME FIRST</span><h1>Resources</h1><p>The worker waits for spare capacity and yields when your server gets busy.</p></div><span className={'status-pill '+(stale?'':'settled')}>{stale?'Telemetry unavailable or stale':'Updated '+Math.round(age!)+'s ago'}</span></div>
    <div className="resource-grid"><Metric label="Host CPU" value={s?.host_cpu_percent==null?'Unavailable':s.host_cpu_percent.toFixed(1)+'%'} help="Total server usage"/><Metric label="App CPU" value={s?.app_cpu_percent==null?'Unavailable':s.app_cpu_percent.toFixed(1)+'%'} help="Owned worker processes"/><Metric label="Available memory" value={bytes(s?.memory_available_bytes)} help="Unified host memory; GPU memory is not added twice"/><Metric label="App memory" value={bytes(s?.app_rss_bytes)} help={s?.app_memory_scope||'Application memory is unavailable'}/><Metric label="GPU utilization" value={s?.gpu?.utilization==null?'Unavailable':s.gpu.utilization+'%'} help="Host-wide, including shared inference"/><Metric label="Free storage" value={bytes(s?.disk_free_bytes)} help="Output and private data filesystem"/></div>
    <div className="resource-grid"><Metric label="CPU thread budget" value={s?.active_cpu_threads==null?'Unavailable':`${s.active_cpu_threads} reserved / ${s.allowed_cpu_threads} currently allowed`} help="The budget follows spare CPU cores; it is not a fixed CPU quota"/><Metric label="Host memory reserve" value={bytes(data.policy.host_memory_reserve_bytes)} help="Reserved for other workloads before admitting new work"/><Metric label="App memory limits" value={s?.enforcement?`${bytes(s.enforcement['memory.high'])} soft / ${bytes(s.enforcement['memory.max'])} hard`:'Unavailable'} help="Actual live worker and slice limits; admission also checks free host memory"/><Metric label="CPU quota throttling" value={s?.application_quota_throttling?.recent_throttled_percent==null?'Unavailable':s.application_quota_throttling.recent_throttled_percent.toFixed(2)+'%'} help={s?.enforcement?.cpu_quota_known?(s.enforcement.cpu_quota_cores==null?'No fixed CPU quota; idle scheduling remains enforced':`Live quota: ${s.enforcement.cpu_quota_cores} cores`):'Live CPU quota is unavailable'}/><Metric label="Shared inference" value={s?.ollama?.status!=='Available'?'Unavailable':s.external_model_connections>0?'Other inference is active':s.ollama.other_models_loaded?'Another model is loaded':s.ollama.selected_model_loaded?'Local clue model is loaded':'Idle'} help="Shared GPU inference cannot be instantly preempted; new model work waits for a safe window"/>{(['cpu','memory','io'] as const).map(kind=><Metric key={kind} label={kind.toUpperCase()+' pressure'} value={s?.psi?.[kind]?.some?.avg10==null?'Unavailable':s.psi[kind].some.avg10.toFixed(2)+'%'} help="Host stall time over the last 10 seconds"/>)}</div><section className="panel"><h2>Worker status</h2><p>{data.reason||(data.active?'Work is running at the lowest priority.':'Waiting for the next eligible task.')}</p><p>{data.active} active task{data.active!==1?'s':''} · {data.waiting} queued or waiting</p><details><summary>Resource policy and enforcement</summary><pre>{JSON.stringify({policy:data.policy,cgroup:s?.cgroup,pressure:s?.psi,shared_inference:s?.ollama},null,2)}</pre></details></section></>;
}
function Metric({label,value,help}:{label:string;value:string;help:string}){return <article className="metric"><small>{label}</small><strong>{value}</strong><p>{help}</p></article>;}
function Settings({prefs,save,notify,install,installed}:{prefs:Prefs;save:(v:Partial<Prefs>,version?:number)=>Promise<void>;notify:(s:string)=>void;install:any;installed:()=>void}){
  const [maintenance,setMaintenance]=useState<any>(null);useEffect(()=>{void api('maintenance').then(setMaintenance).catch(()=>{});},[]);const [value,setValue]=useState(prefs);const [dirty,setDirty]=useState(false);useEffect(()=>{if(!dirty)setValue(prefs);},[prefs,dirty]);const edit=(next:Prefs)=>{setValue(next);setDirty(true);};
  const submit=async()=>{try{const {version,...values}=value;await save(values,version);setDirty(false);}catch(e){notify(String(e));}};
  return <><div className="page-heading"><div><span className="eyebrow">ONE WORKSPACE, SHARED PREFERENCES</span><h1>Settings</h1><p>Changes apply to all authorized devices.</p></div></div><section className="panel settings">{dirty&&prefs.version!==value.version&&<div className="banner">Settings changed on another device. Reload before saving. <button onClick={()=>{setValue(prefs);setDirty(false);}}>Reload settings</button></div>}<h2>Generation</h2><label>Default variants per lesson<input type="number" min="1" step="1" value={value.default_count} onChange={e=>edit({...value,default_count:Number(e.target.value)})}/></label><label>Appearance<select value={value.theme} onChange={e=>edit({...value,theme:e.target.value as Prefs['theme']})}><option value="system">Follow system</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label className="checkbox"><input type="checkbox" checked={value.background_prepare} onChange={e=>edit({...value,background_prepare:e.target.checked})}/>Prepare clues after import when resources are idle</label><p className="hint">Clue preparation uses the local model. It is disabled by default and waits while inference is busy.</p><details><summary>Concurrency preferences</summary>{(['search_slots','threads_per_search','document_slots'] as const).map(k=><label key={k}>{readable(k)}<input type="number" min="1" max={k==='threads_per_search'?8:2} value={value[k]} onChange={e=>edit({...value,[k]:Number(e.target.value)})}/></label>)}<p className="hint">The server enforces its safe deployment ceilings and may admit fewer tasks under load.</p></details><button className="primary" onClick={()=>void submit()}>Save settings</button></section>
    <section className="panel"><h2>Storage and maintenance</h2>{maintenance?<><p>{maintenance.saved_pdfs} saved PDFs · {(maintenance.pdf_bytes/1048576).toFixed(1)} MiB · {maintenance.source_documents} source documents</p><p className="hint">{maintenance.archive_policy}</p><small>Vocabatron {maintenance.version}</small></>:<p>Storage information is unavailable.</p>}</section><section className="panel"><h2>Keep Vocabatron close</h2><p>Install this app for a dedicated window. Your private network connection is still required.</p>{install?<button onClick={async()=>{await install.prompt();await install.userChoice;installed();}}>Install app</button>:<p className="hint">On iPhone or iPad: open this page in Safari, tap Share, then Add to Home Screen. On desktop or Android: use your browser’s Install app option when available.</p>}<p className="hint">Offline access includes the app shell only. Private documents and lesson data are never stored by the service worker.</p></section></>;
}
